controller_manager:
  ros__parameters:
    update_rate: 100
    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    gripper_controller:
      type: effort_controllers/JointGroupEffortController
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      
arm_controller:
  ros__parameters:
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    joints:
      - servo1_waist_joint
      - servo2_arm1_joint
      - arm1_servo3_joint
      - micro_servo1_arm3_joint
      - micro_servo2_gripper_base_joint
      - micro_servo3_gear2_joint
      - gripper_base_gear1_joint
      - gripper_base_up_right_gripper_link_joint
      - gripper_base_up_left_gripper_link_joint
      - gripper_base_down_right_gripper_link_joint
      - gripper_base_down_left_gripper_link_joint
      - gear2_right_gripper_joint
      - gear1_left_gripper_joint

gripper_controller:
  ros__parameters:
    joints: 
    - gear2_right_gripper_joint  
    - gear1_left_gripper_joint 
    command_interfaces:
      - effort
    state_interfaces:
      - position
      - velocity
      - effort
    action_monitor_rate: 20
    goal_tolerance: 0.01
    max_effort: 100
    allow_stalling: true
    stall_velocity_threshold: 0.001
    stall_timeout: 1.0